language: python

services:
  - docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/devops:latest .

jobs:
  include:
    - stage: "Tests"
      script:
      - docker run $DOCKER_USERNAME/devops:latest carta-devops test
    - stage: "Publish"
      script: docker push $DOCKER_USERNAME/devops:latest

