language: python

services:
  - docker

before_install:
- docker build -t unclelobs/devops:latest .

script:
- docker run unclelobs/devops:latest test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master